//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GEAA_Config.Ressources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class geea {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal geea() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GEAA_Config.Ressources.geea", typeof(geea).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le nom du fichier joint du mail contient [{0}].
        /// </summary>
        internal static string AttachmentConditionTextFormat {
            get {
                return ResourceManager.GetString("AttachmentConditionTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mots.
        /// </summary>
        internal static string BodyConditionDefaultValueText {
            get {
                return ResourceManager.GetString("BodyConditionDefaultValueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le contenu du mail contient [{0}].
        /// </summary>
        internal static string BodyConditionTextFormat {
            get {
                return ResourceManager.GetString("BodyConditionTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sauf si.
        /// </summary>
        internal static string Except {
            get {
                return ResourceManager.GetString("Except", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to direction.
        /// </summary>
        internal static string MessageDirectionConditionDefaultValueText {
            get {
                return ResourceManager.GetString("MessageDirectionConditionDefaultValueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La direction du mail est {0}.
        /// </summary>
        internal static string MessageDirectionConditionTextFormat {
            get {
                return ResourceManager.GetString("MessageDirectionConditionTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to direction.
        /// </summary>
        internal static string MessageTypeConditionDefaultValueText {
            get {
                return ResourceManager.GetString("MessageTypeConditionDefaultValueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La type du mail est {0}.
        /// </summary>
        internal static string MessageTypeConditionTextFormat {
            get {
                return ResourceManager.GetString("MessageTypeConditionTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mots.
        /// </summary>
        internal static string Mots {
            get {
                return ResourceManager.GetString("Mots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email.
        /// </summary>
        internal static string RecipientConditionDefaultValueText {
            get {
                return ResourceManager.GetString("RecipientConditionDefaultValueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le(s) destinataire(s) inclu(s) [{0}].
        /// </summary>
        internal static string RecipientConditionTextFormat {
            get {
                return ResourceManager.GetString("RecipientConditionTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;oui/non.
        /// </summary>
        internal static string SecureMessageConditionDefaultValueText {
            get {
                return ResourceManager.GetString("SecureMessageConditionDefaultValueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le message est securisé [{0}].
        /// </summary>
        internal static string SecureMessageConditionTextFormat {
            get {
                return ResourceManager.GetString("SecureMessageConditionTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email.
        /// </summary>
        internal static string SenderConditionDefaultValueText {
            get {
                return ResourceManager.GetString("SenderConditionDefaultValueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le nom de l&apos;emmeteur contients [{0}].
        /// </summary>
        internal static string SenderConditionTextFormat {
            get {
                return ResourceManager.GetString("SenderConditionTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mots.
        /// </summary>
        internal static string SubjectConditionDefaultValueText {
            get {
                return ResourceManager.GetString("SubjectConditionDefaultValueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le Titre du mail contient les mots suivants [{0}].
        /// </summary>
        internal static string SubjectConditionTextFormat {
            get {
                return ResourceManager.GetString("SubjectConditionTextFormat", resourceCulture);
            }
        }
    }
}
